# Generated by Django 2.2 on 2019-04-18 14:20

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='products/%Y/%m/%d'),
        ),
    ]
