# Generated by Django 2.2 on 2019-04-18 14:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190418_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
